source "http://rubygems.org"

ruby "2.2.1"
gem 'rails', ">= 4.2.0"
gem 'sqlite3'
gem 'benchmark-ips'
gem 'redis'
gem 'email_engine', path: '../../'

#=> Scheduling Gems
gem "sidekiq", "~> 3.2.5"
gem 'sidekiq-rate-limiter', :require => 'sidekiq-rate-limiter/server'
gem "sidekiq-failures", "~> 0.4"
gem 'sidekiq-unique-jobs'
gem "sidetiq", "~> 0.6"
gem "sinatra", "~> 1.4.5", require: false
gem "sucker_punch"

gem "faker", "~> 1.6.3"